const KEY="nebula-students-v1";
const seed=[
{id:"s1",name:"林子轩",chinese:96,math:98,english:94,updated:"2026-09-28"},
{id:"s2",name:"沈佳怡",chinese:94,math:93,english:96,updated:"2026-09-27"},
{id:"s3",name:"周宇航",chinese:88,math:96,english:91,updated:"2026-09-25"},
{id:"s4",name:"许安然",chinese:92,math:86,english:90,updated:"2026-09-22"},
{id:"s5",name:"顾思齐",chinese:85,math:89,english:87,updated:"2026-09-21"},
{id:"s6",name:"陈嘉禾",chinese:78,math:81,english:84,updated:"2026-09-20"},
{id:"s7",name:"唐婉宁",chinese:72,math:76,english:79,updated:"2026-09-19"},
{id:"s8",name:"赵明远",chinese:62,math:57,english:68,updated:"2026-09-18"}];
let students=read();let toastTimer;
const $=s=>document.querySelector(s);
function read(){try{const x=JSON.parse(localStorage.getItem(KEY));return Array.isArray(x)?x:seed.map(x=>({...x}))}catch{return seed.map(x=>({...x}))}}
function save(){localStorage.setItem(KEY,JSON.stringify(students))}
function total(s){return +s.chinese + +s.math + +s.english}
function avg(s){return(total(s)/3).toFixed(1)}
function status(n){return n>=270?["excellent","优秀"]:n>=240?["good","良好"]:n>=180?["pass","合格"]:["attention","需关注"]}
function tone(n){return["#e9efff","#e5f7ef","#fff1d9","#ffedf2"][n.charCodeAt(0)%4]}
function safe(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function visible(){let q=($("#tableSearch").value+" "+$("#globalSearch").value).trim().toLowerCase(),f=$("#filter").value,s=$("#sort").value,r=students.filter(x=>{let n=total(x);return(!q||x.name.toLowerCase().includes(q))&&(f==="all"||(f==="excellent"&&n>=270)||(f==="good"&&n>=240&&n<270)||(f==="pass"&&n>=180&&n<240)||(f==="attention"&&n<180))});return r.sort((a,b)=>s==="asc"?total(a)-total(b):s==="name"?a.name.localeCompare(b.name,"zh-CN"):total(b)-total(a))}
function renderStats(){let count=students.length,mean=count?students.reduce((a,x)=>a+total(x),0)/count/3:0,top=[...students].sort((a,b)=>total(b)-total(a))[0];$("#total").textContent=count;$("#average").textContent=mean.toFixed(1);$("#highest").textContent=top?total(top):0;$("#topName").textContent=top?top.name:"暂无";$("#attention").textContent=students.filter(x=>total(x)<180).length}
function renderChart(){let type=$("#subject").value,labels=["90–100","80–89","70–79","60–69","0–59"],colors=["blue","green","amber","amber","red"],b=[0,0,0,0,0];students.forEach(s=>{let v=type==="total"?total(s)/3:+s[type],i=v>=90?0:v>=80?1:v>=70?2:v>=60?3:4;b[i]++});let max=Math.max(...b,1);$("#chart").innerHTML=labels.map((l,i)=>`<div class="chart-column"><span class="bar-number">${b[i]}</span><div class="bar-track"><div class="bar ${colors[i]}" style="height:${Math.max(b[i]/max*100,b[i]?8:2)}%"></div></div><span class="bar-label">${l}</span></div>`).join("")}
function renderRanking(){let r=[...students].sort((a,b)=>total(b)-total(a)).slice(0,4);$("#ranking").innerHTML=r.map((s,i)=>`<div class="rank"><span class="rank-no">${String(i+1).padStart(2,"0")}</span><div class="rank-main"><span class="rank-avatar" style="background:${tone(s.name)}">${s.name[0]}</span><div><div class="rank-name">${safe(s.name)}</div><div class="rank-detail">平均分 ${avg(s)}</div></div></div><strong class="rank-score">${total(s)}</strong></div>`).join("")||"<p>暂无成绩数据</p>"}
function renderTable(){let r=visible();$("#count").textContent=r.length;$("#summary").textContent=`显示 ${r.length} 位学生`;$("#empty").hidden=!!r.length;$("#tbody").innerHTML=r.map(s=>{let [cl,label]=status(total(s));return`<tr><td><div class="student"><span class="student-avatar" style="background:${tone(s.name)}">${s.name[0]}</span><div><b>${safe(s.name)}</b><small>${s.updated} 更新</small></div></div></td><td>${s.chinese}</td><td>${s.math}</td><td>${s.english}</td><td class="score">${total(s)}</td><td>${avg(s)}</td><td><span class="status ${cl}">${label}</span></td><td><div class="row-actions"><button data-a="edit" data-id="${s.id}" title="编辑">✎</button><button data-a="delete" data-id="${s.id}" title="删除">⌫</button></div></td></tr>`}).join("")}
function render(){renderStats();renderChart();renderRanking();renderTable()}
function openModal(s){$("#form").reset();$("#error").textContent="";$("#editId").value=s?.id||"";$("#modalTitle").textContent=s?"编辑学生":"添加学生";$("#submit").textContent=s?"✓ 保存修改":"✓ 保存学生";if(s){$("#name").value=s.name;$("#chinese").value=s.chinese;$("#math").value=s.math;$("#english").value=s.english}updatePreview();$("#modal").hidden=false;document.body.style.overflow="hidden";setTimeout(()=>$("#name").focus(),20)}
function closeModal(){$("#modal").hidden=true;document.body.style.overflow=""}
function updatePreview(){$("#preview").textContent=["#chinese","#math","#english"].reduce((a,s)=>a+(+$(s).value||0),0)}
function toast(msg){$("#toast span").textContent=msg;$("#toast").classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>$("#toast").classList.remove("show"),2200)}
$("#form").addEventListener("submit",e=>{e.preventDefault();let id=$("#editId").value,name=$("#name").value.trim(),scores=[+$("#chinese").value,+$("#math").value,+$("#english").value];if(!name){$("#error").textContent="请输入学生姓名。";return}if(students.some(s=>s.name===name&&s.id!==id)){$("#error").textContent="这个学生已经存在，请检查姓名。";return}if(scores.some(n=>!Number.isInteger(n)||n<0||n>100)){$("#error").textContent="三科成绩必须是 0 到 100 之间的整数。";return}let data={name,chinese:scores[0],math:scores[1],english:scores[2],updated:new Date().toISOString().slice(0,10)};if(id){students=students.map(s=>s.id===id?{...s,...data}:s);toast("学生成绩已更新")}else{students.push({id:"s"+Date.now(),...data});toast("学生已添加")}save();render();closeModal()});
$("#addBtn").onclick=()=>openModal();$("#close").onclick=closeModal;$("#cancel").onclick=closeModal;$("#subject").onchange=renderChart;$("#filter").onchange=renderTable;$("#sort").onchange=renderTable;$("#tableSearch").oninput=renderTable;$("#globalSearch").oninput=e=>{$("#tableSearch").value=e.target.value;renderTable()};["#chinese","#math","#english"].forEach(s=>$(s).oninput=updatePreview);$("#viewAll").onclick=()=>$("#students").scrollIntoView({behavior:"smooth"});$("#clear").onclick=()=>{$("#tableSearch").value=$("#globalSearch").value="";$("#filter").value="all";renderTable()};
$("#tbody").onclick=e=>{let b=e.target.closest("button"),s=b&&students.find(x=>x.id===b.dataset.id);if(!s)return;if(b.dataset.a==="edit")openModal(s);if(b.dataset.a==="delete"&&confirm(`确定删除“${s.name}”的成绩记录吗？`)){students=students.filter(x=>x.id!==s.id);save();render();toast("学生记录已删除")}};
$("#exportBtn").onclick=()=>{let a=document.createElement("a"),u=URL.createObjectURL(new Blob([JSON.stringify(students,null,2)],{type:"application/json"}));a.href=u;a.download=`学生成绩-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(u);toast("成绩数据已导出")};document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();$("#globalSearch").focus()}if(e.key==="Escape"&&!$("#modal").hidden)closeModal()});render();
